languageCode = "sk"
title = "Svadba"
baseURL = "https://repik.sk/kucovci/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = "kucovci"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
defaultContentLanguage = "sk"

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
# [params.posts]
     folderName = ""
#     pageSize = "6"
#     featuredPost = true
#     paginationPages = 2
#     showFirstLast = false
 
[languages]
[languages.sk]
  languageName = "Slovenčina"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
